OpenPetra:
    MainMenu:
        # to activate the plugin
        Custom: {Label=Favoriten, Icon=partner.ico, DependsOnLedger=true}
            Favoriten: {DontShowNestedTasksAsLinks=true}
                Spendenbuchhaltung: {Namespace=Ict.Petra.Client.MFinance.Gui.Gift, DontShowNestedTasksAsLinks=true}
                        TreasurerNotification: {Description: "Briefe und Emails an Finanzminister", Namespace=Ict.Petra.Plugins.TreasurerNotification.Client, ActionOpenScreen=TFrmTreasurerNotification, Label="Treasurer Briefe", PermissionsRequired=FINANCE-1}

